---
- name: Install statsdaemon
  yum: pkg=statsdaemon state=installed
  when: ansible_os_family == "Debian"

- name: Install statsdaemon
  yum: pkg=statsdaemon state=installed
  when: ansible_os_family == "RedHat"

- name: Install statsdaemon configuration
  template:
      src: statsdaemon.ini.j2
      dest: /etc/statsdaemon.ini

- name: Ensure statsdaemon is started and enabled on boot
  service:
      name: statsdaemon
      state: started
      enabled: "{{ statsdaemon_enabled_on_boot }}"
