---
- name: Converge
  hosts: all
  become: true

  vars:
      repository: 'raintank/raintank'

  pre_tasks:
      - when: ansible_os_family == 'RedHat'
        set_fact:
            os: 'el'
            version: '{{ ansible_distribution_major_version }}'

      - when: ansible_distribution == 'Debian'
        set_fact:
            os: 'Debian'
            version: 'jessie'

      - when: ansible_distribution == 'Ubuntu'
        set_fact:
            os: 'ubuntu'
            version: 'xenial'

  roles:
    - role: computology.packagecloud
    - role: Duologic.statsdaemon
